Yaml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -32,14 +32,19 @@ jobs:
           P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
           MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
         run: |
-          echo "$P12_BASE64" | base64 --decode > cert.p12
-          echo "$MOBILEPROVISION_BASE64" | base64 --decode > profile.mobileprovision
+          printf '%s' "$P12_BASE64" | base64 --decode > cert.p12
+          printf '%s' "$MOBILEPROVISION_BASE64" | base64 --decode > profile.mobileprovision
+
+          openssl pkcs12 -in cert.p12 -noout -passin pass:"$P12_PASSWORD" && echo "P12 OK" || echo "P12 ERROR"
 
           security create-keychain -p "temp123" build.keychain
           security default-keychain -s build.keychain
           security unlock-keychain -p "temp123" build.keychain
-          security import cert.p12 -k build.keychain -P "Pronto40" -A
-          security set-key-partition-list -S apple-tool:,apple: -s -k "temp123" build.keychain
+          security list-keychains -s build.keychain
+
+          security import cert.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
+          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "temp123" build.keychain
+
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
 
